name: DevSecOps Pipeline
on:
  push:
    branches: [ "main", "master" ] # Chạy khi code được push vào nhánh main hoặc master

jobs:
  # JOB 1: SAST - Quét mã nguồn tĩnh bằng SonarCloud
  sast-scan:
    name: SAST (SonarCloud)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # SonarCloud cần lịch sử git đầy đủ để phân tích
      
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Token có sẵn của GitHub
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}    # Token bạn vừa thêm vào Secret

  # JOB 2: DAST - Tấn công thử nghiệm bằng OWASP ZAP
  dast-scan:
    name: DAST (OWASP ZAP)
    runs-on: ubuntu-latest
    needs: sast-scan # Chỉ chạy DAST sau khi SAST đã chạy xong
    steps:
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.12.0
        with:
          # --- THAY LINK WEB RENDER CỦA BẠN VÀO DÒNG DƯỚI ---
          target: 'https://devsecops-pipeline-e21h.onrender.com/'
          
          # Tùy chọn: Không làm fail pipeline nếu tìm thấy lỗi (để bạn xem được báo cáo)
          fail_action: false 
          
      - name: Upload ZAP Report
        # Upload báo cáo kể cả khi bước trên bị lỗi
        if: always() 
        uses: actions/upload-artifact@v4
        with:
          name: ZAP-Security-Report
          path: report_html.html
